name: build from source

on:
  push:
    paths:
      - .github/workflows/build.yaml
      - build/*
      - VERSION
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - build/*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set version
        id: version
        run: echo "version=`cat VERSION`" >> $GITHUB_ENV
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/imsingee/protonmail-bridge
          tags: |
              type=ref,event=branch
              type=sha
              type=raw,value=${{ env.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./build
          build-args: |
            version=${{ env.version }}
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
